language: node_js
node_js:
  - "6.6"
  - "8.1"
  - "8.9"
  - "latest"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run cover

after_success:
  - npm run codecov